### ISSUE TITLE
Première installation Leia

### ISSUE THREAD

**Issue by adulescente** [Nux007/Kodi-Super-Favourites-Xmltv#5]
Coucou!
Premièrement, WOW!!! Mais quelle différence.... La rapidité d'exécution n'est même pas comparable avec ton ancienne version... BRAVO! Tu as fais un super job!!!

Bon, alors maintenant, voici mes commentaires quant à ma première utilisation:
1.  SFX , dès la première configuration, m'a donné un message d'erreur lorsqu'il est venu le temps de charger les logos... J'ai réessayé 2 fois, obtenant le même message.  Je suis donc retourné a la configuration pour ''décocher'' l'option ''utiliser les logos du fichier XML'' puis tout est entré dans l'ordre.

2. J'ai, pour l'instant, aucun problème pour ouvrir une chaîne.  Tout fonctionne rapidement et efficacement.

3. Je vais maintenant aller installer mes logos manuellement...  J'ai effectué un premier ''upload'' de logo pour une chaîne et ceci semble avoir fonctionné...  Je ne suis pas allé voir encore.  La seule chose est qu'on me demande de redémarrer SFX pour que mes changements soient pris en charge.  Est-ce que je devrai le faire pour chacune des chaines oèu j'irai installer un logo??

Alors voilà, je te fais parvenir mes logs...  Par contre, et c'est vraiment chiant, j'ai eu un plantage lorsque j'ai voulu allez le visionner avant de l'uploader grrrrr.... les joies de kodi...  Alors je te donne old.log, espérant que tu y trouveras l'information recherchée....

Dernière chose, Tu m'a demandé d'aussi te faire parvenir ''step to reproduce''... Je ne sais pas dutout ce que c'est ou comment faire pour t'acheminer cette info... Comme tu vois, je suis très loin de posséder ton niveau de connaissance ;)  Mais si tu peux me donner la marche a suivre, il me fera plaisir de le faire!

https://drive.google.com/open?id=1QBvtSsZ5k6PBrNhYVPigRpM6GfRu-AfdjGiHDnUPAF4

https://paste.kodi.tv/pokopupilo

Voilà!
Je te tiens au courant pour la suite!

A+
Jue

**Comment by adulescente** [comment]
Pour les logos, l'ajout que j'avais fait pour une chaîne n'a pas fonctionné... 
Je suis donc retourné à la configuration puis j'ai coché à nouveau l'option de prendre les logos via le fichier xml... TADAM! ça a fonctionné instantanément.
![screenshot002](https://user-images.githubusercontent.com/37155801/43746145-81bd945c-99b0-11e8-97dc-c8b707a40b65.png)

**Comment by Nux007** [comment]
> SFX , dès la première configuration, m'a donné un message d'erreur lorsqu'il est venu le temps de charger les logos... J'ai réessayé 2 fois, obtenant le même message. Je suis donc retourné a la configuration pour ''décocher'' l'option ''utiliser les logos du fichier XML'' puis tout est entré dans l'ordre``

En fait, ce n'est pas un message d'erreur, c'est un retour que j'affiche quand un logo n'est pas disponible, mais si tu ne comprends pas le pourquoi du message, ca veut dire que ce n'est pas clair, je vais donc supprimer le message ( que je pensai utile, mais il semble trop ambigu ).

>Je vais maintenant aller installer mes logos manuellement... J'ai effectué un premier ''upload'' de logo pour une chaîne et ceci semble avoir fonctionné... Je ne suis pas allé voir encore. La seule chose est qu'on me demande de redémarrer SFX pour que mes changements soient pris en charge. Est-ce que je devrai le faire pour chacune des chaines oèu j'irai installer un logo??

Tu n'est pas obligée de redémarrer, tu peux les changer les uns à la suite des autres, les changements sont pris en compte directement, mais le nouveau logo ne sera affiché qu'au prochain chargement du groupe de chaines actuellement visible, concrètement pour voir les changements, soit tu redémarre, soit tu passe au groupe de chaines suivant ( flèche du bas ), ensuite, les nouvelles infos seront chargées, 
j'ai opté pour cette solution temporaire pour éviter les refresh intempestifs qu'on avait dans la première version, mais j'ai déjà une solution en tête en écrivant ces lignes ;-)  ...

>Dernière chose, Tu m'a demandé d'aussi te faire parvenir ''step to reproduce''... Je ne sais pas du tout ce que c'est ou comment faire pour t'acheminer cette info... Comme tu vois, je suis très loin de posséder ton niveau de connaissance ;) Mais si tu peux me donner la marche a suivre, il me fera plaisir de le faire!

C'est ma faute, j'ai encore fait du franglais lol, c'est simplemet me décrire les étapes effectuées pour pouvoir reproduire le bug, mais pour l'instant tu n'en as pas encore trouvé qui soit critique, ce qui est une bonne chose pour moi lol :)

>Pour les logos, l'ajout que j'avais fait pour une chaîne n'a pas fonctionné...
Je suis donc retourné à la configuration puis j'ai coché à nouveau l'option de prendre les logos via le fichier xml... TADAM! ça a fonctionné instantanément.

Pourrais tu essayer à nouveau de changer le logo d'une chaine, et  m'envoyer les logs stp ?

Merci pour ton aide, j'apprécie ...

**Comment by Nux007** [comment]
Voila la beta 2 avec le message sur les logos supprimmés, et une mise à jour sur l'utilisation u système de logs internes.
https://github.com/Nux007/Kodi-Super-Favourites-Xmltv/archive/1.1.2.bata02.tar.gz

**Comment by adulescente** [comment]
Merci pour tes réponses :)

Je crois avoir un bug, malheureusement.... et... c'est au niveau de l'horaire des programes... en fait, il y a un ÉNORME décalage ! Et il m'est impossible d'aller ajuster lheire...

Il y a 5 heures de différence avec l'horaire réelle et ce, sur toute mes chaînes.

Mon installation kodi est sur langage "français'" et non "français canada".. tu crois que ça a un lien??

Présentement, j'ai pas le temps de t'envoyer mes logs et tout ce que j'ai essayer comme démarche pour régler le tout mais je te reviens plus en détail ce soir

A+
Jue

**Comment by Nux007** [comment]
Ca ne semble pas etre un bug, as tu essayé de désactiver le "timeshift epg" dans les  parametres  optionnels avant de mettre ton timeshift à toi ? je ferai un nouveau test avec une source fr demain matin pour voir ...

**Comment by adulescente** [comment]
Je vais voir ça...
Je suis québécoise... Mais mon guide comporte des chaines de la france et du Québec.

**Comment by adulescente** [comment]
Ha!! et c'est vrai!!
Ya aussi le fait que j'ai réglé ma ligne temporelle a 3 heures... si j'avance au delà de ça, et bien au lieu d'afficher la programmation, le guide horaire change de page...

Désolée de t'envoyer toute cette info en Vrak comme ça hihi!!!  Je voulais seulement pas oublier...  je viendrai relire tout ceci ce soir lorsque j'aurai le temps et te donnerai les logs et info de façon plus constructive ;)

A+
Jue

**Comment by Nux007** [comment]
C est chouette... tu teste le  soir et je corrige le matin lol...

**Comment by adulescente** [comment]
Hello!

Désolée pour hier soir... me suis endormi vraiment tôt... Alors, j'étais debout vraiment très très tôt ce matin également ihi...

Mon portable principal étant parti pour la journée, j'en ai profité pour installer ta beta2 sous krypton...
Je n'aiabsolument 
AUCUN ug a signaler jusqu'a présent... Vraioment aucun!  En fait, même mon horaire s'est rétablie... Je crois que mon problème initial venait pas de sfx... Je suis allé chez mon fournisseur (je suis abonnée a EPGfor IPTP) et j'ai réglé mon time zone directement de la.  Je n'ai pas activé le timeshift de sfx comme tu me l'a suggéré et voila. Tout va comme sur des roulettes.  Je suis aussi capable d'avancer dans le temps sans changer de page...

MAIS!
Si je veux vraiment t'aider, je vais cesser de chouchouter ton addon en lui donnant un petit peu plus de difficultés hihhi...

Je vais donc aller enlever, modifier des chaînes, changer des logos, ajouter, etc.... 

D'ici la, je t'envoie quand-même mes logs au cas ou tu y verrais des trucs qui pourraient t'être utiles

A+!
Jue
[kodi.log](https://github.com/Nux007/Kodi-Super-Favourites-Xmltv/files/2270786/kodi.log)
[sfx_log.txt](https://github.com/Nux007/Kodi-Super-Favourites-Xmltv/files/2270787/sfx_log.txt)

**Comment by Nux007** [comment]
j ai regardé les logs... tout semble bien fonctionner :-) par contre c'est quoi ton fournisseur ? car je vois que beaucoup de logos sont indisponibles ....

**Comment by Nux007** [comment]
Toujours en trouvé ?
