### ISSUE TITLE
the url as  http://xxxxxx/xmltv.tar.gz doesn't work

### ISSUE THREAD

**Issue by Goga777** [Nux007/Kodi-Super-Favourites-Xmltv#6]
if i will enter xmlt url as  http://xxxxxyyyyy.net/xmltv.tar.gz than i will have the error - no xmltv file found inside of archive

but in the reality xmltv file there is inside of tar.gz archive

kodi log
https://slexy.org/view/s20YgOZpBT

**Comment by Goga777** [comment]
i have sent it through email on your gmail address

**Comment by Nux007** [comment]
It sounds like the file your provider gave you is not a tar.gz, I got an "invalid header" message, it is much more like a bz2 compression format... I'm trying to find a workaround

**Comment by Nux007** [comment]
I found a workaround, will implement it...
