### ISSUE TITLE
Chaînes sans info dans le guide ne s'enlèvent pas

### ISSUE THREAD

**Issue by adulescente** [Nux007/Kodi-Super-Favourites-Xmltv#8]
Bonjour!!

Lorsque je désire retirer une chaine du guide qui n'a pas d'info, ça ne fonctionne pas.

Je suis dans ta release bêta 3 et pour je ne sais quelle raison, j'ai oublié de me remettre en mode debug..   je ne peux donc pas tenvoyer mon log..

Merci et au plaisir!

**Comment by Nux007** [comment]
Salut ! merci pour le feedback, je vais y regarder ;-)

**Comment by Nux007** [comment]
Je viens d'y regarder, c'est un bug que j'avais déjà trouvé et corrigé, le meilleur serait d'attendre la beta01 de la branche beta, qui devrait sortir d'ici quelques jours...
